#!/usr/bin/env bash
# use scp to move files from client to a server
# scp -i <key lives>  <file> ubuntu@18.208.222.5:~/
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi 
