#!/usr/bin/env bash
# install nginx on web-01 server (./1)
# redirect with sed to /redirect_me
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

searchString="^\tlocation / {"
replaceString="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwui4;\n\t}\n\n\tlocation / {"

sudo sed -i "s@${searchString}@${replaceString}@" /etc/nginx/sites-available/default

sudo service nginx restart
