#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

strF="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_back\n\n"
strB="\nbackend custom_back\n\tbalance roundrobin\n\tserver web-01 18.208.222.5:80 check\n\tserver web-02 54.146.253.171:80 check\n"

sudo echo -e $strF | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e $strB | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart                                 
