#!/usr/bin/env bash
# write a program that prints with a 2s sleep
# pgrep sends a signal to a process
# $(command) is a synonym for `command` stands for command substitution;
# "kill" "$(pid returned by command sub)" 
kill "$(pgrep -f 4-to_infinity_and_beyond)"
