#!/usr/bin/env bash
# write fizzbuzz in bash schript
n="100"
for ((i=1; i<=n; i++));
do
    if [ $((i%3)) = 0 ] && [ $((i%5)) = 0 ]; then
        echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]; then
        echo "Fizz"
    elif [ $((i%5)) = 0 ]; then
        echo "Buzz"
    else
        if [ $((i%3)) != 0 ] || [ $((i%5)) != 0 ]; then
            echo $i
        fi
    fi
done
    
