#!/usr/bin/env bash
# print variable with while loop
word=$"Holberton School"
number=1
x=$number
while [ $x -le 10 ]; 
do	
	echo $word
        if [ $x == '9' ]
        then
		echo "Hi"
	fi
        x=$((x+1))
done
