#!/usr/bin/env bash
# print variable with while loop
number=1
x=$number
while [ $x -le 20 ]; 
do	
	echo $x

case $x in
	4 )
		echo "bad luck in China";;
	8 )
		echo "bad luck in Japan";;
	17 )
		echo "bad luck in Italy";;
	esac
        x=$((x+1))
done
