#!/usr/bin/env bash
# use if / else statements to return info about afile
theFile="holbertonschool"
    if [ -e $theFile ];then
        echo "$theFile file exists"
        if [ -s $theFile ]; then
            echo "$theFile file is not empty"
        else
            echo "$theFile file is empty"
        fi
        if  [ -f $theFile ]; then
                echo "$theFile is a regular file"
        fi
    else
        echo "$theFile file does not exist" 
    fi
